### ISSUE TITLE
Add a tour & travel project.

### ISSUE THREAD

**Issue by Haris-Mohanty** [rudra016/WebDev-OpenSource#11]
Hi @rudra016 ,

I hope this message finds you well. I'd like to propose the idea of adding a "Tour & Travel" project to our open-source organization/repo. 

I'm enthusiastic about contributing to this project and would be thrilled to help initiate it. Looking forward to your feedback and guidance.

**Comment by Haris-Mohanty** [comment]
Could you please assign this issue to me so that I can get started on it?

**Comment by rudra016** [comment]
Assigned @Haris-Mohanty
