### ISSUE TITLE
Movies and Tv-Shows Explorer

### ISSUE THREAD

**Issue by adityakhadeak** [rudra016/WebDev-OpenSource#116]
I want to Add a project called Movies & Tv Shows Explorer
where we can search about movies and tv shows and get information about them
It uses TMDB api

![image](https://github.com/rudra016/WebDev-OpenSource/assets/88097649/04b1658e-0c6b-4429-8064-605e833cc0ed)

![image](https://github.com/rudra016/WebDev-OpenSource/assets/88097649/fb638a77-ca6e-4dcb-9a75-c2ad1e3a63bf)

**Comment by rudra016** [comment]
Closing thks because project already exists.
