### ISSUE TITLE
Adding Etch-A-Sketch

### ISSUE THREAD

**Issue by Yash7426** [rudra016/WebDev-OpenSource#124]
I would like to add Etch-A-Sketch to this repository.
Please assign under hacktoberfest 2023.

**Comment by rudra016** [comment]
Describe more about this

**Comment by Yash7426** [comment]
It is a sketching application in pixelated form.The user can select any color from color palatte and can even generate random colors.
![image](https://github.com/rudra016/WebDev-OpenSource/assets/119874901/bd046fa7-ccba-47c2-8db5-7aadd80874a5)
