### ISSUE TITLE
design fixes of foodapp

### ISSUE THREAD

**Issue by vaibhava17** [rudra016/WebDev-OpenSource#16]
Food App visual changes and layout fixes 

- Card Design 
- Cursor Improvement
- Cards Section Layout

**Comment by vaibhava17** [comment]
pls assign it to me under hacktoberfest

**Comment by akashroy1** [comment]
I don't see any PRs here. Can I start working on it?

**Comment by rudra016** [comment]
It may take 1-2 days for the assigned person to complete the changes, if there's no response i'll assign it to you @akashroy1

**Comment by vaibhava17** [comment]
@rudra016 working on it

**Comment by vaibhava17** [comment]
#107 pr provided
