### ISSUE TITLE
Display Section of Calculator can be typed from keyboard

### ISSUE THREAD

**Issue by SusheelThapa** [rudra016/WebDev-OpenSource#21]
[Calculator.webm](https://github.com/rudra016/WebDev-OpenSource/assets/83917129/9cab67ed-dd64-4ffb-b977-d992b94f9192)

**Comment by rudra016** [comment]
@SusheelThapa Display in the Calculator can already be typed form the keyboard, Maybe you have your NumLock On. If not, Explain more about this Issue.

**Comment by SusheelThapa** [comment]
@rudra016 As in above video sample, we can see that letter has been typed which is in appropriate.

**Comment by SusheelThapa** [comment]
@rudra016, while merging  #23 pull request, lets verify if this is occuring or not..
