### ISSUE TITLE
Adding Header and Footer of Calculator Project

### ISSUE THREAD

**Issue by SusheelThapa** [rudra016/WebDev-OpenSource#22]

**Comment by rudra016** [comment]
Pls Add some ScreenShots of your Idea for me to understand :)

**Comment by SusheelThapa** [comment]
@rudra016  I was planning to add header and footer section for the calculator app. Since #23  leads to overall development of scientific calculator. Let's hold on to this issue.

**Comment by rudra016** [comment]
@SusheelThapa go on with this now
