### ISSUE TITLE
Create a 2048 Game

### ISSUE THREAD

**Issue by Harshit-Chordiya** [rudra016/WebDev-OpenSource#220]
### **Description:**

The goal of this project is to develop  2048 game,this is  a popular puzzle game that challenges players to add numbers on a 4x4 grid to create a value of 2048.The game is  a fun  also a good exercise in problem-solving.

### **Overview:**

-  **Grid:** The game is played on a 4x4 grid where the numbered tiles are placed. The game starts with two tiles, each with a value of either 2 or 4, randomly placed on the grid.
- **Tile Movement:** Players can move the tiles in all four directions. When the player makes a move, all the tiles on the grid slide in that direction. Empty spaces are filled by new tiles that appear with a value of 2 or 4.
- **Combination:** When two tiles with the same value collide as a result of a move, they combine to form a new tile with a value equal to their sum.
- **Scores:** The player's score increases with each combination made. The final goal is to reach a tile with a value of 2048.

Please assign this issue to me under `hacktoberfest` label :)

**Comment by swaleha2002** [comment]
hey @Harshit-Chordiya I would like to work on this project, could you please assign it to me?
