### ISSUE TITLE
Fix Pagination Overlap on trailer Component

### ISSUE THREAD

**Issue by rudra016** [rudra016/WebDev-OpenSource#26]
![image](https://github.com/rudra016/WebDev-OpenSource/assets/94120092/8ff192ea-b680-4243-b7a8-9830d65aa359)
Anyone willing to solve this issue can comment!
Edit : This Issue is in the MovieApp Project in the Repo.

**Comment by KANDUKURIYASWANTH** [comment]
Hello @rudra016 I guess i've understood the problem can i give it a try?

**Comment by rudra016** [comment]
@KANDUKURIYASWANTH sure!
