### ISSUE TITLE
Invalid linking of Contribution.md file

### ISSUE THREAD

**Issue by SusheelThapa** [rudra016/WebDev-OpenSource#3]
https://github.com/rudra016/Web-HacktoberFest-2023/blob/87733d9ccdb45e1a2e4c5eb3dae10cd881786b6f/README.md?plain=1#L9

It should be `CONTRIBUTING.MD` rather it is `Contribution.md`

*Note: Rather than CONTRIBUTING.md, it is better to keep the file name CONTRIBUTION.md*

**Comment by SusheelThapa** [comment]
@rudra016 Please assign me this issue, I will update the README.md along with other markdown files.

**Comment by rudra016** [comment]
Hello, Susheel I have fixed the Linking error as it came into my notice. Tho I will assign you the issue for readme once the event starts i.e. 1oct :)

**Comment by SusheelThapa** [comment]
Sure @rudra016, Excited to work with you buddy

**Comment by rudra016** [comment]
Issue Assigned

**Comment by SusheelThapa** [comment]
@rudra016 Shall I modify whole contribution and readme file?
