### ISSUE TITLE
Platform Knight jump game

### ISSUE THREAD

**Issue by saarimshaikh** [rudra016/WebDev-OpenSource#334]
I want to make a Knight Jump game app in which the character will jump on solid platforms. 
 please assign me this issue and mark it hactoberfest accepted.
Thank you

**Comment by rudra016** [comment]
sure, assigning you

**Comment by saarimshaikh** [comment]
Thanks for assigning

**Comment by saarimshaikh** [comment]
I've added the necessary changes, please have a look.
