### ISSUE TITLE
QR Code Reader : Front-End Project 

### ISSUE THREAD

**Issue by Swap-Nova** [rudra016/WebDev-OpenSource#56]
A web application where the user can use their device camera to scan a QR code and it will lead them to the URL path.
So @rudra016 can I work on this application?

**Comment by rudra016** [comment]
@Swap-Nova Qr scan using a laptop?

**Comment by rudra016** [comment]
@Swap-Nova Can you make it more accessible by adding a drop your Qr or upload your Qr feature for laptop?

**Comment by Swap-Nova** [comment]
There is a library I learned about, and through this, we can make this feature. Moreover the application will be deployed and responsive so that application can be used anywhere.

**Comment by rudra016** [comment]
Great! @Swap-Nova

**Comment by Swap-Nova** [comment]
Also, this code can be used in an existing web application so it can be a added feature as well.
