### ISSUE TITLE
RANDOM PASSWORD Generator 

### ISSUE THREAD

**Issue by Sushilverma002** [rudra016/WebDev-OpenSource#71]
an RANDOM PASSWORD generator which generate the STONG password for user.
![image](https://github.com/rudra016/WebDev-OpenSource/assets/114687502/06de4481-56c8-4378-aacb-e85696691bb4)

hackOctoberFest

**Comment by Sushilverma002** [comment]
@rudra016  have a look!!

**Comment by ANKITy102** [comment]
@rudra016 
I would like to work on this issue.
Could you please assign it to me.
