### ISSUE TITLE
Drumkit application

### ISSUE THREAD

**Issue by Shaurya10101** [rudra016/WebDev-OpenSource#8]
This project involves a simple drumkit application that lets you play sounds ( drums , specific notes ) when you press different keys . Please assign me this under Hacktoberfest 2023

**Comment by rudra016** [comment]
Sure @Shaurya10101, I will assign you as soon as the event starts.

**Comment by rudra016** [comment]
Done

**Comment by Shaurya10101** [comment]
The drum kit has been submitted so please close the issue
