### ISSUE TITLE
Fitness Exercises App

### ISSUE THREAD

**Issue by codrrk08** [rudra016/WebDev-OpenSource#93]
Hi @rudra016, I'm taking on a project that basically provides a platfom for providing all major exercises for different kinds of muscle groups. This website will be based on the React framework. 
If it's okay with you, could you assign me this project. It's my first contribution in Hacktoberfest.

**Comment by rudra016** [comment]
Glad to have you

**Comment by codrrk08** [comment]
Thanks :)
