### ISSUE TITLE
Improved UI of QR Code Generator

### ISSUE THREAD

**Issue by Aditi020** [rudra016/WebDev-OpenSource#99]
Add a Header that also has an additional Dark/Light Feature to it.
Improve the appearance by adding background color and an illustration.

Please assign me this I am very much excited to contribute to HactoberFest.
#Hacktoberfest
#Hacktober2023

![photo_6113894390217947798_w](https://github.com/rudra016/WebDev-OpenSource/assets/92170627/de3bd7e2-b7a9-41bb-a18c-f3140b7434f4)

**Comment by rudra016** [comment]
Great
